#!/sbin/sh
set -e

echo "Starting image upgrader: $(date)"

FULL_IMAGE=0

while read line
do
    set -- $line
    case "$1" in
        format)
            echo "Formating: $2"
            case "$2" in
                system)
                    FULL_IMAGE=1
                    rm -f /data/system.img
                    dd if=/dev/zero of=/data/system.img seek=300K bs=4096 count=0
                    mkfs.ext2 -F /data/system.img
                ;;

                data)
                    for entry in /data/*; do
                        if [ "$entry" != "system.img" ]; then
                            rm -Rf $entry
                        fi
                    done
                ;;

                *)
                    echo "Unknown format target: $2"
                ;;
            esac
        ;;

        load_keyring)
            echo "Loading keyring: $2"
        ;;

        mount)
            case "$2" in
                system)
                    mkdir -p /cache/system
                    mount -o loop /data/system.img /cache/system/
                ;;

                *)
                    echo "Unknown mount target: $2"
                ;;
            esac
        ;;

        unmount)
            case "$2" in
                system)
                    umount /cache/system
                    rmdir /cache/system
                ;;

                *)
                    echo "Unknown mount target: $2"
                ;;
            esac
        ;;

        update)
            echo "Applying update: $2"
            cd /cache
            rm -Rf partitions

            # Start by removing any file listed in "removed"
            if [ "$FULL_IMAGE" = "1" ]; then
                cat recovery/$2 | unxz | tar xf - removed || true
                if [ -e removed ]; then
                    while read file; do
                        rm -Rf $file
                    done < removed
                fi
                rm -f removed
            fi

            # Unpack everything else on top of the system partition
            cat recovery/$2 | unxz | tar xf -
            rm -f removed

            # Process partition images
            while read line; do
                set -- $line

                part=${1##/}
                path=$3

                if [ -e partitions/${part}.img ] && [ -e $path ]; then
                    echo "Flashing ${part} at ${path}"
                    cat partitions/${part}.img > ${path}
                    rm partitions/${part}.img
                fi
            done < /etc/recovery.fstab
        ;;

        *)
            echo "Unknown command: $1"
        ;;
    esac
done < $1

echo "Done upgrading: $(date)"
